name: windows_headless_example

on: workflow_dispatch

jobs:
  demo:
    runs-on: windows-latest
    steps:
      - name: Install Twingate
        run: |
          Invoke-WebRequest https://api.twingate.com/download/windows?installer=msi -OutFile .\twingate_client.msi
          Set-Content .\key.json  '${{ secrets.SERVICE_KEY }}'
          $key_path = (Get-Item .\key.json | Resolve-Path).ProviderPath
          .\twingate_client.msi service_secret=$key_path /qn
          Start-Sleep -Seconds 30
          Get-Service twingate.service
          Start-Service twingate.service
          Start-Sleep -Seconds 10
          Get-Service twingate.service

